packages:
  - packages/*

catalogs:
  typescript:
    '@types/node': ^25.0.3
    node-modules-inspector: ^1.2.0
    typedoc: ^0.28.15
    typescript: ^5.9.3
  voidzero:
    '@vitest/coverage-v8': ^4.0.16
    '@vitest/ui': ^4.0.16
    oxfmt: ^0.21.0
    oxlint: ^1.36.0
    oxlint-tsgolint: ^0.10.0
    publint: ^0.3.16
    tsdown: ^0.18.4
    vite: npm:rolldown-vite@^7.3.0
    vitest: ^4.0.16
