packages:
  - packages/*
  - apps/*

catalogs:
  typescript:
    '@types/node': ^22.12.0
    node-modules-inspector: ^1.2.0
    typedoc: ^0.28.15
    typescript: ^5.9.3
  voidzero:
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    oxfmt: ^0.31.0
    oxlint: ^1.46.0
    oxlint-tsgolint: ^0.11.5
    publint: ^0.3.16
    tsdown: ^0.20.3
    vite: npm:rolldown-vite@^7.3.0
    vitest: ^4.0.18
