/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core'
import {
	HttpClient,
	HttpHeaders,
	HttpParams,
	HttpResponse,
	HttpEvent,
	HttpContext,
} from '@angular/common/http'
import { Observable } from 'rxjs'
import { OpenApiHttpParams, QueryParamStyle } from '../query.params'

// @ts-ignore
import { CreateRegistrationFormRequest } from '../model/createRegistrationFormRequest'
// @ts-ignore
import { ErrorResponse } from '../model/errorResponse'
// @ts-ignore
import { RegistrationForm } from '../model/registrationForm'
// @ts-ignore
import { RegistrationFormPage } from '../model/registrationFormPage'
// @ts-ignore
import { RegistrationFormStatus } from '../model/registrationFormStatus'
// @ts-ignore
import { SubmitRegistrationFormRequest } from '../model/submitRegistrationFormRequest'
// @ts-ignore
import { UpdateRegistrationFormRequest } from '../model/updateRegistrationFormRequest'

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables'
import { Configuration } from '../configuration'
import { BaseService } from '../api.base.service'

export interface CreateRegistrationFormRequestParams {
	createRegistrationFormRequest: CreateRegistrationFormRequest
	/** Idempotency key for safely retrying create requests without creating duplicate registration forms.  */
	xIdempotencyKey?: string
}

export interface GetRegistrationFormDetailRequestParams {
	formId: string
}

export interface ListRegistrationFormsRequestParams {
	status?: RegistrationFormStatus
	/** Keyword to search by form reference or dynamic form values */
	keyword?: string
	page?: number
	size?: number
}

export interface SubmitRegistrationFormRequestParams {
	formId: string
	submitRegistrationFormRequest?: SubmitRegistrationFormRequest
}

export interface UpdateRegistrationFormRequestParams {
	formId: string
	updateRegistrationFormRequest: UpdateRegistrationFormRequest
}

@Injectable({
	providedIn: 'root',
})
export class RegistrationService extends BaseService {
	constructor(
		protected httpClient: HttpClient,
		@Optional() @Inject(BASE_PATH) basePath: string | string[],
		@Optional() configuration?: Configuration,
	) {
		super(basePath, configuration)
	}

	/**
	 * Create a registration form
	 * @endpoint post /api/v1/registrations/forms
	 * @param requestParameters
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 * @param options additional options
	 */
	public createRegistrationForm(
		requestParameters: CreateRegistrationFormRequestParams,
		observe?: 'body',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<RegistrationForm>
	public createRegistrationForm(
		requestParameters: CreateRegistrationFormRequestParams,
		observe?: 'response',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpResponse<RegistrationForm>>
	public createRegistrationForm(
		requestParameters: CreateRegistrationFormRequestParams,
		observe?: 'events',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpEvent<RegistrationForm>>
	public createRegistrationForm(
		requestParameters: CreateRegistrationFormRequestParams,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<any> {
		const createRegistrationFormRequest = requestParameters?.createRegistrationFormRequest
		if (createRegistrationFormRequest === null || createRegistrationFormRequest === undefined) {
			throw new Error(
				'Required parameter createRegistrationFormRequest was null or undefined when calling createRegistrationForm.',
			)
		}
		const xIdempotencyKey = requestParameters?.xIdempotencyKey

		let localVarHeaders = this.defaultHeaders
		if (xIdempotencyKey !== undefined && xIdempotencyKey !== null) {
			localVarHeaders = localVarHeaders.set('X-Idempotency-Key', String(xIdempotencyKey))
		}

		// authentication (BearerAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'BearerAuth',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (OAuth2) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'OAuth2',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (XUserIdAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'XUserIdAuth',
			'X-User-Id',
			localVarHeaders,
		)

		const localVarHttpHeaderAcceptSelected: string | undefined =
			options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json'])
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected)
		}

		const localVarHttpContext: HttpContext = options?.context ?? new HttpContext()

		const localVarTransferCache: boolean = options?.transferCache ?? true

		// to determine the Content-Type header
		const consumes: string[] = ['application/json']
		const httpContentTypeSelected: string | undefined =
			this.configuration.selectHeaderContentType(consumes)
		if (httpContentTypeSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected)
		}

		let responseType_: 'text' | 'json' | 'blob' = 'json'
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
				responseType_ = 'text'
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = 'json'
			} else {
				responseType_ = 'blob'
			}
		}

		let localVarPath = `/api/v1/registrations/forms`
		const { basePath, withCredentials } = this.configuration
		return this.httpClient.request<RegistrationForm>('post', `${basePath}${localVarPath}`, {
			context: localVarHttpContext,
			body: createRegistrationFormRequest,
			responseType: <any>responseType_,
			...(withCredentials ? { withCredentials } : {}),
			headers: localVarHeaders,
			observe: observe,
			...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
			reportProgress: reportProgress,
		})
	}

	/**
	 * Get registration form detail
	 * @endpoint get /api/v1/registrations/forms/{formId}
	 * @param requestParameters
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 * @param options additional options
	 */
	public getRegistrationFormDetail(
		requestParameters: GetRegistrationFormDetailRequestParams,
		observe?: 'body',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<RegistrationForm>
	public getRegistrationFormDetail(
		requestParameters: GetRegistrationFormDetailRequestParams,
		observe?: 'response',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpResponse<RegistrationForm>>
	public getRegistrationFormDetail(
		requestParameters: GetRegistrationFormDetailRequestParams,
		observe?: 'events',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpEvent<RegistrationForm>>
	public getRegistrationFormDetail(
		requestParameters: GetRegistrationFormDetailRequestParams,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<any> {
		const formId = requestParameters?.formId
		if (formId === null || formId === undefined) {
			throw new Error(
				'Required parameter formId was null or undefined when calling getRegistrationFormDetail.',
			)
		}

		let localVarHeaders = this.defaultHeaders

		// authentication (BearerAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'BearerAuth',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (OAuth2) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'OAuth2',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (XUserIdAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'XUserIdAuth',
			'X-User-Id',
			localVarHeaders,
		)

		const localVarHttpHeaderAcceptSelected: string | undefined =
			options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json'])
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected)
		}

		const localVarHttpContext: HttpContext = options?.context ?? new HttpContext()

		const localVarTransferCache: boolean = options?.transferCache ?? true

		let responseType_: 'text' | 'json' | 'blob' = 'json'
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
				responseType_ = 'text'
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = 'json'
			} else {
				responseType_ = 'blob'
			}
		}

		let localVarPath = `/api/v1/registrations/forms/${this.configuration.encodeParam({ name: 'formId', value: formId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`
		const { basePath, withCredentials } = this.configuration
		return this.httpClient.request<RegistrationForm>('get', `${basePath}${localVarPath}`, {
			context: localVarHttpContext,
			responseType: <any>responseType_,
			...(withCredentials ? { withCredentials } : {}),
			headers: localVarHeaders,
			observe: observe,
			...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
			reportProgress: reportProgress,
		})
	}

	/**
	 * Get registration forms
	 * @endpoint get /api/v1/registrations/forms
	 * @param requestParameters
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 * @param options additional options
	 */
	public listRegistrationForms(
		requestParameters?: ListRegistrationFormsRequestParams,
		observe?: 'body',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<RegistrationFormPage>
	public listRegistrationForms(
		requestParameters?: ListRegistrationFormsRequestParams,
		observe?: 'response',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpResponse<RegistrationFormPage>>
	public listRegistrationForms(
		requestParameters?: ListRegistrationFormsRequestParams,
		observe?: 'events',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpEvent<RegistrationFormPage>>
	public listRegistrationForms(
		requestParameters?: ListRegistrationFormsRequestParams,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<any> {
		const status = requestParameters?.status
		const keyword = requestParameters?.keyword
		const page = requestParameters?.page
		const size = requestParameters?.size

		let localVarQueryParameters = new OpenApiHttpParams(this.encoder)

		localVarQueryParameters = this.addToHttpParams(
			localVarQueryParameters,
			'status',
			<any>status,
			QueryParamStyle.Form,
			true,
		)

		localVarQueryParameters = this.addToHttpParams(
			localVarQueryParameters,
			'keyword',
			<any>keyword,
			QueryParamStyle.Form,
			true,
		)

		localVarQueryParameters = this.addToHttpParams(
			localVarQueryParameters,
			'page',
			<any>page,
			QueryParamStyle.Form,
			true,
		)

		localVarQueryParameters = this.addToHttpParams(
			localVarQueryParameters,
			'size',
			<any>size,
			QueryParamStyle.Form,
			true,
		)

		let localVarHeaders = this.defaultHeaders

		// authentication (BearerAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'BearerAuth',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (OAuth2) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'OAuth2',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (XUserIdAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'XUserIdAuth',
			'X-User-Id',
			localVarHeaders,
		)

		const localVarHttpHeaderAcceptSelected: string | undefined =
			options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json'])
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected)
		}

		const localVarHttpContext: HttpContext = options?.context ?? new HttpContext()

		const localVarTransferCache: boolean = options?.transferCache ?? true

		let responseType_: 'text' | 'json' | 'blob' = 'json'
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
				responseType_ = 'text'
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = 'json'
			} else {
				responseType_ = 'blob'
			}
		}

		let localVarPath = `/api/v1/registrations/forms`
		const { basePath, withCredentials } = this.configuration
		return this.httpClient.request<RegistrationFormPage>('get', `${basePath}${localVarPath}`, {
			context: localVarHttpContext,
			params: localVarQueryParameters.toHttpParams(),
			responseType: <any>responseType_,
			...(withCredentials ? { withCredentials } : {}),
			headers: localVarHeaders,
			observe: observe,
			...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
			reportProgress: reportProgress,
		})
	}

	/**
	 * Submit registration form
	 * @endpoint post /api/v1/registrations/forms/{formId}/submit
	 * @param requestParameters
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 * @param options additional options
	 */
	public submitRegistrationForm(
		requestParameters: SubmitRegistrationFormRequestParams,
		observe?: 'body',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<RegistrationForm>
	public submitRegistrationForm(
		requestParameters: SubmitRegistrationFormRequestParams,
		observe?: 'response',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpResponse<RegistrationForm>>
	public submitRegistrationForm(
		requestParameters: SubmitRegistrationFormRequestParams,
		observe?: 'events',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpEvent<RegistrationForm>>
	public submitRegistrationForm(
		requestParameters: SubmitRegistrationFormRequestParams,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<any> {
		const formId = requestParameters?.formId
		if (formId === null || formId === undefined) {
			throw new Error(
				'Required parameter formId was null or undefined when calling submitRegistrationForm.',
			)
		}
		const submitRegistrationFormRequest = requestParameters?.submitRegistrationFormRequest

		let localVarHeaders = this.defaultHeaders

		// authentication (BearerAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'BearerAuth',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (OAuth2) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'OAuth2',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (XUserIdAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'XUserIdAuth',
			'X-User-Id',
			localVarHeaders,
		)

		const localVarHttpHeaderAcceptSelected: string | undefined =
			options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json'])
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected)
		}

		const localVarHttpContext: HttpContext = options?.context ?? new HttpContext()

		const localVarTransferCache: boolean = options?.transferCache ?? true

		// to determine the Content-Type header
		const consumes: string[] = ['application/json']
		const httpContentTypeSelected: string | undefined =
			this.configuration.selectHeaderContentType(consumes)
		if (httpContentTypeSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected)
		}

		let responseType_: 'text' | 'json' | 'blob' = 'json'
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
				responseType_ = 'text'
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = 'json'
			} else {
				responseType_ = 'blob'
			}
		}

		let localVarPath = `/api/v1/registrations/forms/${this.configuration.encodeParam({ name: 'formId', value: formId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/submit`
		const { basePath, withCredentials } = this.configuration
		return this.httpClient.request<RegistrationForm>('post', `${basePath}${localVarPath}`, {
			context: localVarHttpContext,
			body: submitRegistrationFormRequest,
			responseType: <any>responseType_,
			...(withCredentials ? { withCredentials } : {}),
			headers: localVarHeaders,
			observe: observe,
			...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
			reportProgress: reportProgress,
		})
	}

	/**
	 * Update a draft registration form
	 * @endpoint put /api/v1/registrations/forms/{formId}
	 * @param requestParameters
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 * @param options additional options
	 */
	public updateRegistrationForm(
		requestParameters: UpdateRegistrationFormRequestParams,
		observe?: 'body',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<RegistrationForm>
	public updateRegistrationForm(
		requestParameters: UpdateRegistrationFormRequestParams,
		observe?: 'response',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpResponse<RegistrationForm>>
	public updateRegistrationForm(
		requestParameters: UpdateRegistrationFormRequestParams,
		observe?: 'events',
		reportProgress?: boolean,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<HttpEvent<RegistrationForm>>
	public updateRegistrationForm(
		requestParameters: UpdateRegistrationFormRequestParams,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: {
			httpHeaderAccept?: 'application/json'
			context?: HttpContext
			transferCache?: boolean
		},
	): Observable<any> {
		const formId = requestParameters?.formId
		if (formId === null || formId === undefined) {
			throw new Error(
				'Required parameter formId was null or undefined when calling updateRegistrationForm.',
			)
		}
		const updateRegistrationFormRequest = requestParameters?.updateRegistrationFormRequest
		if (updateRegistrationFormRequest === null || updateRegistrationFormRequest === undefined) {
			throw new Error(
				'Required parameter updateRegistrationFormRequest was null or undefined when calling updateRegistrationForm.',
			)
		}

		let localVarHeaders = this.defaultHeaders

		// authentication (BearerAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'BearerAuth',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (OAuth2) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'OAuth2',
			'Authorization',
			localVarHeaders,
			'Bearer ',
		)

		// authentication (XUserIdAuth) required
		localVarHeaders = this.configuration.addCredentialToHeaders(
			'XUserIdAuth',
			'X-User-Id',
			localVarHeaders,
		)

		const localVarHttpHeaderAcceptSelected: string | undefined =
			options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json'])
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected)
		}

		const localVarHttpContext: HttpContext = options?.context ?? new HttpContext()

		const localVarTransferCache: boolean = options?.transferCache ?? true

		// to determine the Content-Type header
		const consumes: string[] = ['application/json']
		const httpContentTypeSelected: string | undefined =
			this.configuration.selectHeaderContentType(consumes)
		if (httpContentTypeSelected !== undefined) {
			localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected)
		}

		let responseType_: 'text' | 'json' | 'blob' = 'json'
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
				responseType_ = 'text'
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = 'json'
			} else {
				responseType_ = 'blob'
			}
		}

		let localVarPath = `/api/v1/registrations/forms/${this.configuration.encodeParam({ name: 'formId', value: formId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}`
		const { basePath, withCredentials } = this.configuration
		return this.httpClient.request<RegistrationForm>('put', `${basePath}${localVarPath}`, {
			context: localVarHttpContext,
			body: updateRegistrationFormRequest,
			responseType: <any>responseType_,
			...(withCredentials ? { withCredentials } : {}),
			headers: localVarHeaders,
			observe: observe,
			...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
			reportProgress: reportProgress,
		})
	}
}
