/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ErrorResponse {
	code: string
	message: string
	details?: Array<string>
}
