/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationFormStatus } from './registrationFormStatus'

export interface RegistrationForm {
	id?: string
	referenceNo?: string
	productCode?: string
	/**
	 * Dynamic form payload; structure is defined by the form template
	 */
	formContent?: { [key: string]: any }
	status?: RegistrationFormStatus
	submittedAt?: string
	createdAt?: string
	updatedAt?: string
}
export namespace RegistrationForm {}
