/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Registration form lifecycle status
 */
export const RegistrationFormStatus = {
	Draft: 'DRAFT',
	Submitted: 'SUBMITTED',
	Approved: 'APPROVED',
	Rejected: 'REJECTED',
	Cancelled: 'CANCELLED',
} as const
export type RegistrationFormStatus =
	(typeof RegistrationFormStatus)[keyof typeof RegistrationFormStatus]
