/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistrationForm } from './registrationForm'

export interface RegistrationFormPage {
	items: Array<RegistrationForm>
	page: number
	size: number
	totalElements: number
	totalPages: number
}
