/**
 * Onboard registration API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateRegistrationFormRequest {
	/**
	 * Dynamic form payload; structure is defined by the form template
	 */
	formContent: { [key: string]: any }
}
